apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magenta-customers.fullname" . }}-config
  labels:
    {{- include "magenta-customers.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | default "docker" | quote }}
