package com.magenta.products.domain.model;

public enum PropertyType {
    FLAT, APARTMENT, STUDIO, HOUSE, VILLA, TOWNHOUSE, DUPLEX, LOFT, PENTHOUSE,
    COUNTRY_HOUSE, RUSTIC_LAND, URBAN_LAND, PARKING, STORAGE_ROOM,
    COMMERCIAL_PREMISES, OFFICE, WAREHOUSE, HOTEL, BUILDING
}
