package com.magenta.servicios.domain.model;

public enum ServiceCode {
    FIRST_HOME_AID,
    MORTGAGE_BROKER,
    BRIDGE_LOAN,
    RENT_DEFAULT_INSURANCE,
    HOME_INSURANCE,
    LIFE_INSURANCE,
    RENT_GUARANTEE,
    APPRAISAL,
    PROFILE_SEARCH,
    PROPERTY_SEARCH,
    LEGAL_REVIEW,
    TECHNICAL_REPORT,
    RENOVATION_QUOTE,
    MOVING,
    UTILITIES_SETUP,
    TAX_ADVISORY,
    NOTARY_GESTORIA
}
